dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_inappwebview: null
description: A new Flutter project.
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=3.1.1 <4.0.0'
flutter:
  assets:
  - assets/webexport/
  uses-material-design: true
name: webvrlauncher
publish_to: none
version: 1.0.0+1
